import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Container } from "../components/Container";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container />
        
        <p id="my-id"></p>
        
        <input id="their-id"></input>
        <button id="make-call">発信</button>
        <video id="their-video" width="400px" autoPlay muted playsInline></video>
      </main>

      <style jsx>{`
        #videoTag {
          display:none;
        }
      `}</style>
    </div>
  )
}
